### ISSUE TITLE
Refine load/save contract for qbeast-spark

### ISSUE THREAD

**Issue by alexeiakimov** [Qbeast-io/qbeast-spark#11]
# Problem

It is necessary to make the qbeast-spark contract more precise in the part responsible for loading and saving indexed data.

Currently, qbeast-spark implements CreatableRelationProvider and RelationProvider traits on the top of Delta Lake. The createRelation methods are generic in terms of supported parameters, namely the parameters of the operation are specified as Map[String, String]. Our implementation passes the received parameters directly to the corresponding Delta Lake API. It means that the customer can use Delta Lake specific parameters to invoke some Delta Lake features like partitioning or user metadata. Our implementation tries to handle those parameters where it is possible.

The problem is that the intent to provide a transparent support of the Delta Lake behind the Qbeast can lead to the situation when the customer expects our system to implement a scenario that is supported by Delta Lake and which is not compatible with our indexing system. For example, at the moment we cannot support the partitioning as it is specified by the customer, we have to extend the partitioning by adding the cube and state fields.

The goal of this task is

1. To specify the features and the corresponding options supported by Qbeast save/load operations
2. To isolate the Delta Lake based implementation from the options which are not supported by Qbeast.
3. If it is necessary to support some Delta Lake features then to define the corresponding Qbeast options and to implement their translation to the original Delta Lake options as a part of the implementation. 

In brief, the proposed approach is to hide the used Delta Lake instance from the direct access by the customer applications. Or course, we cannot hide it completely, because it is in the classpath, however, it should be done at the contract level.

# On the load/save contract

At the moment DataFrameReader and DataFrameWriter are the only API supported by Qbeast for loading and saving data. To be precise only a subset of available methods of DataFrameReader and DataFrameWriter are supported by Qbeast. Below they are described in mo details.

## The load contract

1. Client obtains a DataFrameReader instance from the SparkSession.
2. Client uses "qbeast" as format.
3. Client can specify standard option "timeZone"
4. Client uses one of the "load" methods to load the DataFrame.
5. Alternatively a client can use "qbeast" method with the table path as a shortcut for "format(...).load(...)".
6. Alternatively a client can specify the table path as the "path" option. This scenario is supported by Spark, though it is not recommended.

## The save contract

1. Client obtains a DataFrameWriter instance from the DataFrame "write" method.
2. Client uses the "mode" method to specify the save mode. 
3. Client uses "qbeast" as the format.
4. Client uses "columnsToIndex" option to specify a comma-separated list of columns to be used by the index.
5. Client can specify standard option "timeZone"
6. Client can specify the partition columns using the "partitionBy" method.
7. Client uses the "save" method with the table path to write the data.
8. Alternatively the client can use the "qbeast" method with the table path as a shortcut for "format(...).save(...)".
9. Alternatively the client can specify the table path as the "path" option. This scenario is supported, though is not recommended.
10. The methods "bucketBy", "sortBy", "insertInto" and "saveToTable" are not supported at the moment, because they require a certain type of the underlying table.
11. The methods "csv", "json", "jdbc", "text", "orc", and alike are not supported, because they require a different data format.

# On implementation

QbeastDataSource should remove all unsupported options from the parameters passed to the implementations of TableProvider, CreatableRelationProvider and RelationProvider before those parameters could be passed further to the persistence layer implemented on the top of Delta Lake.

**Comment by osopardo1** [comment]
Cleaning issues, this one is irrelevant for the moment
