### ISSUE TITLE
The same CubeId with different hashCodes

### ISSUE THREAD

**Issue by Jiaweihu08** [Qbeast-io/qbeast-spark#135]
## What went wrong?

The same cube created using two different methods can have different `bitMask`'s. This leads to different hashCodes, making `CubeId` an unreliable candidate as `Map` keys.

## How to reproduce?

```scala
val level65 =
      CubeId(2, "wQwwwQwwQwwQwwwwwQwQwwwQQwwwwQQwQwwwQwwQwwQwwwwwQwwQQQQQQQQQQQQQQ")
      
// cubes from level 64
val cubeThroughParentMethod = level65.parent.get
val cubeThroughConstructor =
      CubeId(2, "wQwwwQwwQwwQwwwwwQwQwwwQQwwwwQQwQwwwQwwQwwQwwwwwQwwQQQQQQQQQQQQQ")

println(cubeThroughParentMethod.bitMask) // Array(-1441504016541484037, -6148914603906580738, 0, 0)
println(cubeThroughConstructor.bitMask) // Array(-1441504016541484037, -6148914603906580738)
```

### 2. Branch and commit id:
`main`, [880203a](https://github.com/Qbeast-io/qbeast-spark/commit/880203addde1cff4a74f0b6b0aece324d900d560)

### 5. How are you running Spark?
Local

**Comment by alexeiakimov** [comment]
Good catch, please do not forget to fix `equals` as well. Thank you.
