### ISSUE TITLE
Add logging on file filtering

### ISSUE THREAD

**Issue by osopardo1** [Qbeast-io/qbeast-spark#179]
## What went wrong?

Right now we don't have an easy way to track how many files are filtered or what are the predicates pushed down to Qbeast. This issue is to add logging on the Query side and bring more information to the user through Spark Logs. 

Feel free to add any suggestion of metrics you would like to see @polsm91 

I suggest to start by:
-  `OTreeIndex` `listFiles` method, which filter the files that does not match the query. 
-  `SampleRule` that pushes down the Sampling arguments.

**Comment by victorcuevasv** [comment]
Created a pull request under the link:
https://github.com/Qbeast-io/qbeast-spark/pull/180
which contains examples of the log messages generated.

**Comment by osopardo1** [comment]
This is closed in #180
