### ISSUE TITLE
Filtering by equality of string leads to a wrong traversal of the tree

### ISSUE THREAD

**Issue by Adricu8** [Qbeast-io/qbeast-spark#190]
## What went wrong?
When we filter by a string column indexed in qbeast-spark we are finding that instead of traversing a specific branch, we also visit sibling cubes that should in theory be avoided.

## Example use-case

```scala
spark.sql("select domain from db.some_table where domain='www.example.domain.com").show(false)
Output cubes: Vector(CubeId(2, 0, ), CubeId(2, 1, g), CubeId(2, 2, gw), CubeId(2, 3, gww), CubeId(2, 4, gwwQ), CubeId(2, 3, gwQ), CubeId(2, 4, gwQw), CubeId(2, 4, gwQQ), CubeId(2, 5, gwQQw), CubeId(2, 5, gwQQQ), CubeId(2, 2, gQ), CubeId(2, 3, gQw), CubeId(2, 4, gQww), CubeId(2, 5, gQwww), CubeId(2, 5, gQwwQ), CubeId(2, 4, gQwQ), CubeId(2, 5, gQwQw), CubeId(2, 5, gQwQQ), CubeId(2, 3, gQQ), CubeId(2, 4, gQQw), CubeId(2, 1, A))
```

The previous query outputs 1 record, yet it reads 160GB (out of 3.5 TB). 
For example: 
`CubeId(2, 4, gwwQ), CubeId(2, 4, gwQw)` sibling cubes are visited

### 2. Branch and commit id: 
main branch

### 3. Spark version:
3.2.2

### 4. Hadoop version:
3.2.2

### 5. How are you running Spark?
on kubernetes

**Comment by osopardo1** [comment]
Thanks for creating the issue!

After merging #189 we can debug this behaviour better and I could create a reproducible example of the issue.

**Comment by Jiaweihu08** [comment]
Is this still an issue or should be closed? @osopardo1 @Adricu8

**Comment by osopardo1** [comment]
This issue is no longer relevant for the current String Indexing implementation in #215.

Closing it.
