### ISSUE TITLE
2 files based optimization

### ISSUE THREAD

**Issue by alexeiakimov** [Qbeast-io/qbeast-spark#196]
## Problem
The current compaction/optimization mechanism has the following pitfalls:

1. Compaction and optimization are considered separately, however it turned out that they are closely related processes, and in many cases they should be performed together.
2. In the resulting files the weights of elements do not have uniform distribution. It has not been a problem until now, but it is a blocker for new implementation of sampling #68.

### Proposal
The new compaction/optimization mechanism is proposed in the following documents:

1. https://docs.google.com/document/d/1RV1SLnvL2uiwYIgniYdAH4yAhtGKp1Yi5nEin0RdHO4/edit
2. https://www.notion.so/qbeastanalytics/Optimization-Draft-for-qbeast-spark-Updated-95cdcbbeb34a4309921e2d91540b88d2

### Scope
The new mechanism should be available via QbeastTable API. In the future the new mechanism will be also available from SQL, but for now it is out of the scope.

### Programming model and new QbeastTable API
Optimization has at least two goals: to make more efficient the file structure of the index and to improve the data outlook while reading the data in particular in the case of sampling. Technically speaking it is a combination of file compaction and data replication. During compaction, many small cube files are joined into two large files. Replication makes cube data also available from the child cubes, which allows to reduce the amount of data to read in the sampling scenario.

Optimization is invoked for each index revision separately. For the staging area optimization is no operation. @cugni  @osopardo1  please confirm.

Compaction is applied to those cubes which have too many files or have a big overflow of elements. Replication is applied to those cubes which are specified explicitly. @cugni, @osopardo1 is appropriate to run replication without compaction? @cugni, @osopardo1 in particular is it OK to replicate the cubes which have not been compacted? 

A possible QbeastTable API can look like the following:

```scala
case class OptimizeParams(
    // The revision identifier.
    revisionId: Int,
    // The limit for the number of cube files.
    fileLimit: Option[Int],
    // The cube overflow limit.
    overflowLimit: Option[Double],
    // The identifiers of the cubes to replicate.
    cubesToReplicate: Set[CubeId]
)

class QbeastTable(...) {
...
def optimize(params: OptimizeParams): Unit = {...}
...
}  
```

### API compatibility
The existing methods `compact` and `optimize` should be marked as deprecated and their implementation should call the new mechanism with some reasonable options. The deprecated methods should not stay in the code for a long time, because at the moment we do not expect many customers to use them.

### Storage compatibility
At the first glance any existing storage can be optimized with a new mechanism, because it will just treat the index as non-optimized. And vice versa the old version can operate a storage optimized with the new mechanism, because the old version does depend on the file name. @cugni, @osopardo1 please confirm.

### Open questions
1. How a user can find out which cubes need replication?
2. Should we provide shortcuts to run compaction for all the revisions with a single call?

**Comment by alexeiakimov** [comment]
The `replicationId` parameter should be optional, if missing the system should use the latest revision.

**Comment by osopardo1** [comment]
How much this issue has diverged from the current development? Should we close it and document a new one?

**Comment by osopardo1** [comment]
How much this issue has diverged from the current development @alexeiakimov ? Should we close it and document a new one?

**Comment by alexeiakimov** [comment]
IMHO it has nothing in common but the name. After a long discussion on 2 file based compaction, @cugni invented rollup compaction theat is being implemented now.

**Comment by osopardo1** [comment]
Closing it due to specific algorithm changes.
