### ISSUE TITLE
Unable to supersede IdentityToZeroTransformation and NullToZeroTransformation

### ISSUE THREAD

**Issue by Jiaweihu08** [Qbeast-io/qbeast-spark#224]
## What went wrong?
Both `IdentityToZeroTransformation` and `NullToZeroTransformation` are designed to handle special instances where `LinearTransformer` is used to map `Numeric` columns, but the values are either identical or all `nulls.` 

Ideally, these should be superseded when appending "regular" data by `LinearTransformation` instances. For now, this is not the case.

## How to reproduce?
These transformations are not superseded by the new `LinearTransformation` and are unable to transform new values that are not 1. the `identityValue`(`IdentityToZeroTransformation`) or `null` (`NullToZeroTransformation`).

```scala
import org.apache.spark.sql.delta.DeltaLog
import io.qbeast.spark.delta.DeltaQbeastSnapshot
import io.qbeast.core.transform.IdentityToZeroTransformation
import spark.implicits._

case class IdentityCls(col1: String, col2: Int, col3: Double)

val idTestPath = "/tmp/test1/"
val identityData = (1 to 1000).map(_ => IdentityCls("1", 1, 1d)).toDS()
(identityData
	.write
	.mode("overwrite")
	.option("columnsToIndex", "col2")
	.option("cubeSize", "10000")
	.format("qbeast")
	.save(idTestPath)
)

(DeltaQbeastSnapshot(DeltaLog.forTable(spark, idTestPath)
  .update())
  .loadLatestRevision
  .transformations
  .head
  .isInstanceOf[IdentityToZeroTransformation]
) // true

// scala.MatchError at io.qbeast.core.transform.IdentityToZeroTransformation.transform(Transformation.scala:56)
((1 to 1000)
  .map(i => IdentityCls(s"$i", i, i.toDouble))
  .toDS()
  .write
  .mode("append")
  .format("qbeast")
  .save(idTestPath)
)
```

### 2. Branch and commit id:
`main`, [f066acf](https://github.com/Qbeast-io/qbeast-spark/commit/f066acfa640e795459bb9ff815b641377660bd43)

### 3. Spark version:
`3.4.1`

### 4. Hadoop version:
`3.3.4`

### 5. How are you running Spark?
Locally

**Comment by osopardo1** [comment]
My initial thoughts on this:

1. IdentityTransformation should NOT be superseded by another IdentityTransformation. (By definition, the space value of Identity A is not considered in Identity B unless value a and value b are the same). 
2. IdentityTransformation should NOT superseded by a NullToZeroTransformation. Same case as the Identity.
3. IdentityTransformation might be superseded by a LinearTransformation if max and min cover the identity value.


Now, in cases 1 and 2, we might require a trigger of another type of transformation, such as LinearTransformation, in which we include values from A and B as the ranges. 

Does it make sense?

**Comment by Jiaweihu08** [comment]
## The creation of NullToZeroTransformation and IdentityToZeroTransformation
The `LinearTransformer` creates both `NullToZeroTransformation` and `IdentityToZeroTransformation` when the input column has only one unique value: 
- `NullToZeroTransformation` when it's full of nulls
- `IdentityToZeroTransformation` otherwise

## What does superseding a Transformation mean?
If a transformation `t1` is superseded by another transformation `t2`, t1.isSupersededBy(t2),` it means that the space of `t2` is not contained in that of `t1` and a larger transformation `t3 = t1.merge(t2)` should be used instead.  

## How to define isSupersededBy?

`NullToZeroTransformation` can only transform `nulls,` so it should be superseded as soon as any other transformation is encountered.

It should be superseded by:
1. `IdentityToZeroTransformation`
2. `LinearTransformation`

And not by:
1. `NullToZeroTransformation`

`IdentityToZeroTransformation(a)` should be superseded by:
1. `NullToZeroTransformation`
2. A different `IdentityToZeroTransformation(b)` where `a != b.`
3. A `LinearTransformation(c, d)` where `a != c.`

## How do we merge?

`NullToZeroTransformation.merge(IdentityToZeroTransformation) => ?`
`NullToZeroTransformation.merge(LinearTransformation) => ?`
`NullToZeroTransformation.merge(NullToZeroTransformation) => ?`

`IdentityToZeroTransformation.merge(NullToZeroTransformation) =>  ?`
`IdentityToZeroTransformation.merge(IdentityToZeroTransformation) => ?`
`IdentityToZeroTransformation.merge(LinearTransformation) => ?`

## What do we do if there are only two values: null and some_value?
