### ISSUE TITLE
Update SBT/scala frameworks

### ISSUE THREAD

**Issue by osopardo1** [Qbeast-io/qbeast-spark#236]
Several things to do in the project regarding SBT and Scala frameworks.

- Right now we are using `scalastyle` to cover the style and productivity of the code. Seems like the project has not been updated for long and `scalafix` could be a better library to use in the project. 
- Update plugins: delete the ones that are not used and update the versions.
- Sbt version: update the version of the SBT building tool to the last one.

**Comment by alexeiakimov** [comment]
I was thinking that the problem is with scalafmt, since the task is to replace scala-style with more modern scalafix, then it looks promising. Apologies.

**Comment by alexeiakimov** [comment]
The update is done for main-1.0.0. I suggest to close the issue.
