### ISSUE TITLE
Add Block Filtering by Weights during Sampling

### ISSUE THREAD

**Issue by Jiaweihu08** [Qbeast-io/qbeast-spark#261]
## What went wrong?
The following image illustrates the weight ranges shift between a cube and its blocks - the more blocks you add to a cube, the smaller its weight range(`[minWeight, maxWeight]`) gets, as a consequence, the less overlaping of weight ranges among the cube blocks. Given enough time, the oldest blocks can even cease to overlap with the cube weights all together,

![weight-drift](https://github.com/Qbeast-io/qbeast-spark/assets/47899566/eb381fa1-cbfa-47c3-866f-ab48fc805aad)

As an attempt to reduce the sampling overhead, blocks from a chosen cube whose weight range doesn't overlap with the query weight range should be filtered out when sampling the index.

## Branch and commit id:
- main: [9083396](https://github.com/Qbeast-io/qbeast-spark/commit/908339665e54a32fa086f5b16036070d91653c8b)
- main-1.0.0: [8bc87dc](https://github.com/Qbeast-io/qbeast-spark/commit/8bc87dc8cb839130f2d82478883d9875e1e4fc65)

### Spark version:
`3.4.2`

### Hadoop version:
`3.3.3`

**Comment by osopardo1** [comment]
Merged on https://github.com/Qbeast-io/qbeast-spark/pull/284
