### ISSUE TITLE
Unexpected idempotent write behavior

### ISSUE THREAD

**Issue by Jiaweihu08** [Qbeast-io/qbeast-spark#274]
The [delta lake protocol](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#transaction-identifiers) states that for the same `txnAppId,` any `txnVersion` **smaller than or equal to** the latest one in the log is to be ignored. At the moment, we are checking for equality only.

In `snapshot.setTransactions`, only the largest `txnVersion` is saved.

```
Map(testApp1 -> 30, testApp2 -> 10)
```

- Branches: `main`, `main-1.0.0`

**Comment by fpj** [comment]
The requirement is captured in this section of the protocol spec:

https://github.com/delta-io/delta/blob/master/PROTOCOL.md#transaction-identifiers
