### ISSUE TITLE
Update Documentation for 0.6.0 release

### ISSUE THREAD

**Issue by osopardo1** [Qbeast-io/qbeast-spark#309]
This issue is to update the documentation for the 0.6.0 release version. 

The TODO list are:

- Update Spark Version on README.
- Update Delta Version (and packages) on README.
- Update Compatibility Matrix on README.
- Update Spark & Delta Versions on CONTRIBUTING.

**Comment by osopardo1** [comment]
Also @fpj noticed that the import of QbeastTable in the README.md is not working for the new version code. Would fix in the same PR #310

**Comment by fpj** [comment]
Fixed with PR #310
