### ISSUE TITLE
Incorrect Rollup cube element counts

### ISSUE THREAD

**Issue by Jiaweihu08** [Qbeast-io/qbeast-spark#315]
## What went wrong?
Stale **blocks** have **offsets** that belong to the subtree due to the constant evolution of the **index**.

When optimizing such an index, the number of elements for each cube is unknown and can only be obtained after the records are indexed.

We now compute the cube element counts using their current value, ignoring the fact that **offsets** no longer belong to the current cube.

#### Hadoop version: `3.3.4`

**Comment by cdelfosse** [comment]
To be added to 0.6.0 rc2
