### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by Jiaweihu08** [Qbeast-io/qbeast-spark#359]
Update `CONTRIBUTING.md` with more detailed PR guidelines.

To open and merge PRs, the following is to be respected:
1. Always open an issue for the PR you're working with as much detail as possible
2. Every PR should have an issue that it is trying to address, ideally one
3. The title of the PR should follow the schema: `Issue <issue-number>: <PR-title>`
4. Ideally, there should be at least two reviewers per PR
5. The author of the PR never gets to merge the PR; a PR can only be merged by a reviewer
6. Do a `Squash and merge` instead of `merge,` again, by a reviewer

**Comment by osopardo1** [comment]
Aaaaaah I forget to add as well that every PR should be linked to an issue (I know is implicit in the steps, but ........)

**Comment by osopardo1** [comment]
Merged on #376
