### ISSUE TITLE
Qbeast Spark Refactor: Delta abstraction

### ISSUE THREAD

**Issue by osopardo1** [Qbeast-io/qbeast-spark#398]
We noticed that some parts of the core/common code are still dependent of the Delta Format, losing its intention of sharing code between implementations.

One task to make the code more flexible is splitting the Qbeast Internals (such as the `RollUpWriter`) from their dependencies.

**Comment by osopardo1** [comment]
Here are some more ideas about the changes:

- We should decouple the code in three layers:
    - **Engine** (spark): this is where all the heavy work happens: how we write and index the data, execute optimizations... It should include all the Datasource utilities for registering the table/dataset, although this part would eventually disappear to a more "optionable" way of writing with Qbeast (perhaps included in the third layer).
    - **Core**: this package should contain all the interfaces for refining the Layout in a format-agnostic manner. Instead of relying on `FileAction` or Delta's `Snapshot`, we should define Qbeast own API's for retrieving and managing metadata and layout. The main entry point can be the `QbeastSnapshot`. It is complicated to detach the core module from the Spark engine, since the DataFrame/Dataset API is very powerful to manipulate both data and metadata. 
    - **Format** (delta): this last layer should contain the implementations of `core` that are dependent of the Format. For example, the Metadata Commit Protocol and the encapsulation of the transaction. As well as all the retrieval methods to build the `QbeastSnapshot`.

**Comment by osopardo1** [comment]
For the `RollupDataWritter` part:

- Leave DataWriter method and interface simple: just write a DataFrame in files according to the TableChanges and produce a sequence of IndexFile with metadata as a result.
- Move the `Rollup` code to the `OTreeSparkManager`, more precisely into the optimize method.

**Comment by cugni** [comment]
I would organize the 3 modules slightly  differently: 
- **core** contains all the algorithms and various computations using a spark as an engine. We should use only Dataframes and SparkSession, but not internal Spark API. For instance, here I would put:
   -  the data model
   - The OTreeAnalyzer
   - RollupDataWriter
   - OpenTable API (QbeastSnapshot, etc.). 

- **Format** modules (Delta/Hudi/Iceberg): the adapters of any open table format. These modules should only depend on the core. 

- **Spark integration**: this module binds everything together, registers the data source and SQL extension, and provides any User interface. For instance:
    -  DataSources
    -  SQLextensions
    -  User interface (e.g., QbeastTable)
    -  Any "glue" code, that connects different modules. 
    - Anything that depends on Spark internals. 
    
```mermaid
flowchart RL;
   Q[ Qbeast Spark] --> OTI[Delta - Hudi - Iceberg];
   Q[ Qbeast Spark] --> core[Qbeast Core];
   OTI --> core
```
