### ISSUE TITLE
Validate Code Refactoring for Functional and Performance Regression

### ISSUE THREAD

**Issue by JosepSampe** [Qbeast-io/qbeast-spark#433]
We need to validate the recent code refactoring (delta abstraction issue #398) by performing the following checks:

- **Functional Validation**: Ensure that all existing tests pass successfully without any failures. This will confirm that the refactored code retains the expected behavior.
- **Performance Regression**: Compare the performance of the refactored code against the master branch and validate if any performance degradation exists.
- **Sandbox Installation**: Verify that the refactored code works in production-like environments, including installation, deployment, and real-world use cases. Ensure that the changes integrate seamlessly with production workflows.

**Comment by osopardo1** [comment]
For the Sandbox installation, I think we can use the [qbeast-testing project](https://github.com/Qbeast-io/qbeast-testing). 

It misses the Autoloader component, but it adds a Kubernetes deployment with the corresponding configuration (same that we are using in production). I can guide you through it tomorrow!

**Comment by JosepSampe** [comment]
Duplicated in ZH
