### ISSUE TITLE
Merge Refactoring Branch into Main

### ISSUE THREAD

**Issue by JosepSampe** [Qbeast-io/qbeast-spark#447]
- Update the refactoring branch with the latest changes from the main branch, as new PRs have been merged into the main branch since the refactoring started.
- Resolve all conflicts that arise during the merge.
- Validate that all new logic introduced in the main branch since the refactoring started is present and has not been removed. Also, ensure that all changes made in the refactoring branch are still intact.

**Comment by osopardo1** [comment]
Merged in #446
