### ISSUE TITLE
 Allow MetadataManager to pass commitTimestamp to DataWriter

### ISSUE THREAD

**Issue by JosepSampe** [Qbeast-io/qbeast-spark#465]
Currently, the commitTimestamp is created inside `MetadataManager`, but there is no mechanism to pass it to `DataWriter`. Some table formats require this timestamp to generate filenames and populate additional metadata columns during writes. This enhancement will allow the MetadataManager to provide the commitTimestamp to the `DataWriter`, enabling format-specific handling of filenames and extra columns.

Acceptance Criteria:

- Implement a way for `MetadataManager` to transfer commitTimestamp to `DataWriter`.
- Ensure `DataWriter `can use the commitTimestamp for filename generation and additional columns as required by specific table formats.
- Maintain backward compatibility for cases where commitTimestamp is not needed by the `DataWriter`.
- Have at least one test case that reproduces the issue and shows that the code changes fix it.

**Comment by fpj** [comment]
I added one more item to the acceptance criteria.
