### ISSUE TITLE
Losing records when cubeSize is too small

### ISSUE THREAD

**Issue by osopardo1** [Qbeast-io/qbeast-spark#47]
**What went wrong?**
On the PR #39 we were testing different indexing columns. Running an indexing test with a `DataFrame` of size `1000` and `cubeSize` of `10` in an 8 core spark standalone process, we found out it is not reading all the information.

**Why?**

Estimation computed in `CubeWeights` can be suboptimal for small cube size. For example:

We set an overall cubeSize of 100. We have 5 partitions with the following number of elements on each one:

`[92, 52, 22, 50, 10]`

The max weight of the root cube should be: `100/(92 + 52 + 22 + 50 + 10) = 0.442 `

Now, some test with random distributions:
If we follow the actual implementation, the desiredSize for each partition is going to be 100 / 5 = 20. 

With a program in Python we generate a list of random number for each partition with the size that corresponds, and we picked the element at 20th position (if existed). The results were:

`[0.133, 0.4516, 0.87, 0.39, 2]`

When we estimate the max weight, the result is: `0.0713 * 5 (num of partitions) = 0.3565`

But if we do the same operation for a cubeSize of 1000, desiredSize per partitions 1000/5 = 200, the result equals to: `0.089 * 5 = 0.44` which is closer to the real value of `0.442`

This leads to cubes having a very small estimation of their max weight on the first step of the algorithm. Then, when trying to put the actual records on the cubes, those with lower precision are skipped, and everything is stored in the children. The result of this is that all data is written correctly, but cubes are missing. And reading protocol does not expect this behavior in the structure. 

**Possible solution**

To solve this we must set a minimum default cube size and let it be configurable on a SparkSession level (not as an option to a DataFrame). 

**How to reproduce?**
1. Code that triggered the bug, or steps to reproduce:
 
This is the code to reproduce the error:

```scala

case class T1(a: Int, b: String, c: Double)

 val source = 0
      .to(1000)
      .map(i => T1(i, s"$i", i.toDouble))
      .toDF()
      .as[T1]

    source.write
      .format("qbeast")
      .option("columnsToIndex", "a,c")
      .option("cubeSize", 10)
      .save(tmpDir)

    val indexed = spark.read
      .format("qbeast")
      .load(tmpDir)
      .as[T1]

    source.count() shouldBe indexed.count()

```
2. Branch and commit id:

[divide-et-impera](https://github.com/cugni/qbeast-spark/tree/divide-et-impera) at e059768f8cab6a3a0d6d1a9eaf7fe3d222e9b40c

3. Spark version:
On the spark shell run `spark.version`.

3.1.1

4. Hadoop version:
On the spark shell run `org.apache.hadoop.util.VersionInfo.getVersion()`.

3.2.0

5. Are you running Spark inside a container? Are you launching the app on a remote K8s cluster? Or are you just running the tests in a local computer?

Local
6. Stack trace:

**Comment by cugni** [comment]
this should be fixed now with the current version.  I run the example code and it works. I'll close the issue, @osopardo1 , @eavilaes let me know if there something else in it.
