### ISSUE TITLE
Include INSERT INTO in Qbeast save contract

### ISSUE THREAD

**Issue by osopardo1** [Qbeast-io/qbeast-spark#5]
**What went wrong?**
Right now on the master, we cannot add new elements to a qbeast table through the INSERT INTO sql command

**How to reproduce?**
1. Code that triggered the bug, or steps to reproduce:

On a previously indexed dataframe named df:

```scala 
df.createOrReplaceTempView("t")
spark.sql("insert into table t (value) values (4)")
```

And the output is: 

```
org.apache.spark.sql.AnalysisException: QbeastBaseRelation(parquet) does not allow insertion.;
'InsertIntoStatement Relation[value#1297] QbeastBaseRelation(parquet), false, false
+- LocalRelation [col1#1543]

  at org.apache.spark.sql.execution.datasources.PreWriteCheck$.failAnalysis(rules.scala:512)

```

2. Branch and commit id:

master ef6b9f45ac54ab156e5b3474e3014b639b2ac827

3. Spark version:
3.x

4. Hadoop version:

2.4.7

5. Are you running Spark inside a container? Are you launching the app on a remote K8s cluster? Or are you just running the tests in a local computer?
Local

6. Stack trace:

**Comment by eavilaes** [comment]
Solved by #116
