### ISSUE TITLE
Qbeast Optimize breaks columns stats format when the min (or max) value is a string, but the value is a number. 

### ISSUE THREAD

**Issue by cugni** [Qbeast-io/qbeast-spark#509]
## What went wrong?
I've indexed a large dataset (500 GB) with Qbeast, where one of the columns is named "title." After several incremental appends, I've run a full Qbeast optimize, but the JSON commit log is corrupted, as it happens that some rows have a number as a value, and it gets encoded as int instead of a string. 
So the last _delta_log file looks like this:
```json
{
  "numRecords": 50148,
  "minValues": {
    "title": 1997
  },
  "maxValues": {
    "title": "Veilchen",
  },
  "nullCount": {
    "text": 0,
  }
}
```
Where the title is a string, but in this file, it happens that the min value equals the number 1997, and for some reason, is then encoded as `1997` instead of `"1997"`
## How to reproduce?

It happened when indexing this dataset: https://huggingface.co/datasets/Upstash/wikipedia-2024-06-bge-m3. I'll try to create a smaller code snippet to recreate the issue in a smaller environment. 
Different steps about how to reproduce the problem.

### 1. Code that triggered the bug, or steps to reproduce:
I reproduced the error with both Apache Spark and deltalake. Hter the stack error in Spark:
```
Caused by: org.apache.spark.sql.catalyst.util.BadRecordException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('1' (code 49)): was expecting comma to separate Object entries
 at [Source: (byte[])"{"add":{"path":"355e1315-857f-4cee-bbac-4b4210c235ce.parquet","partitionValues":{},"size":299950993,"modificationTime":1733747878484,"dataChange":false,"stats":"{\"numRecords\":68001,\"minValues\":{\"url\":\"https://en.wikipedia.org/wiki/19\",\"text\":\"\\t//the array that will be sorted\",\"weight_partition\":0.0,\"id\":2428414.23,\"title\":"1927",\"text_size\":100},\"maxValues\":{\"url\":\"https://en.wikipedia.org/wiki/An?\",\"text\":\"? ,  Australasia (ANZ) was a com?\",\"weight_partiti"[truncated 701 bytes]; line: 1, column: 347]

```
```scala
// your-code-here
```

### 3. Spark version:
3.5.3

### 5. How are you running Spark?
SLURM
### 6. Stack trace:
Trace of the log/error messages.

**Comment by osopardo1** [comment]
I've noticed the behavior you mentioned in the JSON with this small test, but I cannot see an error reading the DF nor the DeltaLog.

```scala
import spark.implicits._
val data = spark.range(1000).withColumn("name", col("id").cast(StringType))
data.write.format("qbeast").option("columnsToIndex", "name").save(tmpDir)

val indexed = spark.read.format("qbeast").load(tmpDir)
indexed.filter(col("name") === "1").count() shouldBe 1

val deltaLog = DeltaLog.forTable(spark, tmpDir)
val allFiles = deltaLog.update().allFiles
allFiles.map(_.stats).collect().foreach(println)

```

Result is:

```bash
{"numRecords":1000,"minValues":{"name":0,"id":0},"maxValues":{"name":999,"id":999},"nullCount":{"name":0,"id":0}}
```

Which is the query/operation you are trying to run on top of this dataset?
