### ISSUE TITLE
Transform recursive method findSampleFiles to iterative

### ISSUE THREAD

**Issue by osopardo1** [Qbeast-io/qbeast-spark#56]
`findSampleFiles` method was implemented as a recursive function to filter those files needed for the query. 

https://github.com/Qbeast-io/qbeast-spark/blob/d9bd04aa17f60b2ca3e2f7143193e931ab40d389/src/main/scala/io/qbeast/spark/delta/OTreeIndex.scala#L121

This code is going to be called every time a qbeast dataset is read, so we need to make sure it takes as few resources as possible. An iterative solution can be a good approach!

**Comment by osopardo1** [comment]
@alexeiakimov if you can take this ticket would be fantastic!

**Comment by cugni** [comment]
This can probably be solved together with PR #57 (where I think @Jiaweihu08 is working now), as we will have to change that part.

**Comment by osopardo1** [comment]
Yes, I assignee him the task! And marked as In Progress as well.
