### ISSUE TITLE
Overhead of qbeast_hash filtering when doing a Sample

### ISSUE THREAD

**Issue by osopardo1** [Qbeast-io/qbeast-spark#68]
**What went wrong?**
When a sample() is performed against a qbeast dataset, the qbeast sql extension changes the Sample operation into a Filter to:
- Pushdown the filter to the data source
- Filter the cubes that satisfy the [lowerBound, upperBound]
- In the end, read less data

But in this process, we are producing a hash in memory of the columns indexed to make sure that the records matched with the Sample range. 
This hash has an extra cost when we don't need the information of those columns to satisfy the query. For example, if we have a dataset indexed by `(user_id,product_id)` and we want to know the avg `price`, we are **avoiding the pruning of `user_id, product_id` columns**. 

We need to study how to overcome this problem. 
One solution is to avoid the in-memory filtering for those files that have a `maxWeight < upperBound`, because we know for sure that all the records in that file match the predicate.

**Comment by Adricu8** [comment]
We can just use Random.nextInt() to implement the qbeast_hash function and forget about the indexed columns (only for writing). The complex part comes when we read the data. Two options could be to either write a random weight per cube (user invasive) or create the random weight in memory to use it to filter the data per cube.

**Comment by osopardo1** [comment]
Due to the complexity of adding these changes to the code, we will postpone the solution of this issue.

Keep in mind that the only case affected on performance is when reading a SAMPLE of files.
