### ISSUE TITLE
Slow Collect and Execute on QbeastWriter during indexing

### ISSUE THREAD

**Issue by polsm91** [Qbeast-io/qbeast-spark#8]
**What went wrong?**

During the indexing of a dataset of 12.4GB using 2 numerical columns one of the most time-consuming jobs have been to execute and collect in the QbeastWriter on the following line:
https://github.com/Qbeast-io/qbeast-spark/blob/15667c27bb2cc6d76cecd680d61e22fa8f571d49/src/main/scala/io/qbeast/spark/sql/qbeast/QbeastWriter.scala#L171
https://github.com/Qbeast-io/qbeast-spark/blob/15667c27bb2cc6d76cecd680d61e22fa8f571d49/src/main/scala/io/qbeast/spark/sql/qbeast/QbeastWriter.scala#L173

![slowCollext Execute](https://user-images.githubusercontent.com/22685017/134489485-d49b9550-99e5-4948-be5a-1fc4bf78aff3.png)

## Hypothesis and know issue

Our current implementation for writing data is split into two stages

1. **Calculation of an estimated CubeWeight map**. 
    It is done by partition and requires a collect() in order to broadcast the variable and be able to put each row in a correspondent cube. Plus, **aggregation of min/max of the columns indexed** is required to know the space we are indexing. 

2. **Reorganization of data and writing of multiple rows of the same cube in a single parquet file**
    1. Repartition the data by cube and state. Minor penalization is equivalent to delta writing time. 
    2. File I/O writing. All the records from a cube are written in a **single parquet file**, not allowing the parallelization of the write operation.

As documented by @alexeiakimov :

An attempt to index 1GB of data on a single node with qbeast-spark-nodep_2.12-nightly-d44ce4c.jar has shown that the following three jobs are the main contributors to the time:

1. **execute and collect() at QbeastWriter- 2.4 min**. Method collect is called on the dataset after all the records are written to destination media
https://github.com/Qbeast-io/qbeast-spark/blob/15667c27bb2cc6d76cecd680d61e22fa8f571d49/src/main/scala/io/qbeast/spark/sql/qbeast/QbeastWriter.scala#L171
https://github.com/Qbeast-io/qbeast-spark/blob/15667c27bb2cc6d76cecd680d61e22fa8f571d49/src/main/scala/io/qbeast/spark/sql/qbeast/QbeastWriter.scala#L173
2. **min/max aggregation**. **Model - 1.8 min**. Method agg is called on the dataset to compute min and max values for each dimension
https://github.com/Qbeast-io/qbeast-spark/blob/15667c27bb2cc6d76cecd680d61e22fa8f571d49/src/main/scala/io/qbeast/spark/model/Model.scala#L213
3. **collect() on** **OTreeAlgorithm - 1.7 min**. Method collect is called on the dataset to compute the cube weights.
https://github.com/Qbeast-io/qbeast-spark/blob/15667c27bb2cc6d76cecd680d61e22fa8f571d49/src/main/scala/io/qbeast/spark/index/OTreeAlgorithm.scala#L248

The hypothesis is that in all three cases the traversing of the full dataset is responsible for the big latency. It is clear that in the `ColumnInfo` case our code has minimal impact, because it simply computes min and max for two columns, however, it has a latency of the same magnitude as `QbeastWriter` and `OTreeAlgorithm`, where we do a lot of computations.

**How to reproduce?**
1. Code that triggered the bug, or steps to reproduce:
- Relevant config for the SparkSession in the Azure Cluster:
```
            --packages org.apache.hadoop:hadoop-azure:2.7.0,com.azure:azure-storage-blob:12.8.0,com.azure:azure-storage-common:12.8.0,com.microsoft.azure:azure-storage:2.0.0,io.delta:delta-core_2.12:0.8.0 \
            --conf spark.executor.cores=3 \
            --conf spark.driver.memory=12g \
            --conf spark.executor.memory=12g \
            --conf spark.eventLog.enabled=true \
            --conf spark.sql.extensions=io.qbeast.spark.sql.QbeastSparkSessionExtension \
            --conf spark.driver.extraJavaOptions="-Dqbeast.index.size=2000000""

```
- We load the table `store_sales` from the TPC-DS 100Gb dataset, which has a size of 12.4GB in delta format. We index it by using the primary key attributes and we write them on qbeast format:

```scala 
val store_sales = spark.read.format("delta").load("wasb://tpc-ds@blobqsql.blob.core.windows.net/data-1gb/store_sales")
val tmpDir = "wasb://tpc-ds@blobqsql.blob.core.windows.net/qb_indexed_1gb/store_sales"
store_sales.write.mode("overwrite").format("qbeast").option("columnsToIndex", "ss_item_sk,ss_ticket_number").save(tmpDir)
```

2. Branch and commit id:
Main on 15667c27bb2cc6d76cecd680d61e22fa8f571d49

3. Spark version:
3.1.1

4. Hadoop version:
2.7

5. Are you running Spark inside a container? Are you launching the app on a remote K8s cluster? Or are you just running the tests in a local computer?
Running Spark Shell from the Jupyter Notebook in the Kubernetes deployment on Azure

**Comment by cugni** [comment]
@polsm91 do you think this bug is still relevant?

**Comment by osopardo1** [comment]
I don't think this is still relevant. Cleaning a bit the issues :smile:
