### ISSUE TITLE
ColumnsToIndex and/or CubeSize should be optional on Append

### ISSUE THREAD

**Issue by osopardo1** [Qbeast-io/qbeast-spark#81]
When writing data with `qbeast` format, the user needs to specify every time the `columnsToIndex` or `cubeSize`. This is ok if you want to change them, but it shouldn't be always explicit.

For example, if the user wants to append data to an existing table and maintain the same configuration, it should be able to write:

```scala
df.write.format("qbeast").save("existing-path")
```

instead of
```scala
df.write.format("qbeast").mode("append").option("columnsToIndex", "x,y,z").option("cubeSize", "10000").save("existing-path")
```

**Comment by eavilaes** [comment]
I agree that options should be maintained if appending, but I don't know if `append` should be inferred if the file exists. Shouldn't we throw an Exception in this case?
I think it is better to specify it, so: 
```scala
df.write.format("qbeast").mode("append").save("existing-path")
```
