### ISSUE TITLE
Pull Request Template not working

### ISSUE THREAD

**Issue by eavilaes** [Qbeast-io/qbeast-spark#92]
## What went wrong?
On [#87 Documentation Improvements](https://github.com/Qbeast-io/qbeast-spark/pull/87) we added a [pull_request_template.md](https://github.com/Qbeast-io/qbeast-spark/blob/main/.github/PULL_REQUEST_TEMPLATE/pull_request_template.md). 

For some reason, when trying to open a Pull Request, this file is **not being used**.
I would **expect** something like the following image to be shown, but the body of the Pull Request is empty by default.

<img width="600" alt="Screenshot 2022-03-25 at 12 14 34" src="https://user-images.githubusercontent.com/34559457/160111172-837c281d-4c1b-44a0-a7e5-072f1e897b24.png">

It is a minor issue, but It would be great to have it working ☺️

**Comment by osopardo1** [comment]
Seems to be related to this https://stackoverflow.com/questions/52139192/github-pull-requests-template-not-showing

I will move the template to the `.github` folder :runner: 

Thank you!
